name: Secure CI Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: npm install

      - run: node app.js

      - run: npm audit

      - name: Secure Secret Usage
        run: echo "Running securely"
        env:
          PASSWORD: ${{ secrets.APP_PASSWORD }}
